name: Matrix Bundled

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  job:
    name: "${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            triplet: x64-linux
            output: build/Test
          - os: windows-latest
            triplet: x64-windows
            output: build/Release/Test.exe
          - os: macos-latest
            triplet: x64-osx
            output: build/Test

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
    - name: Prepare upload folder
      run: |
        mkdir Artefact
        mkdir Artefact/${{ matrix.os }}
        
        mv ${{ matrix.output }} Artefact/${{ matrix.os }}
      
    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: Executables
        path: Artefact
        
